services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=rocketseat
      - MYSQL_PASSWORD=MinhaSenhaDoMySql2026
      - MYSQL_ROOT_PASSWORD=MinhaSenhaDoMySql2026
    networks:
      - primeira-network

  api-rocket:
    build: .
    container_name: api-rocket
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    external: true
    driver: bridge

volumes:
  db:
